INSERT INTO CONS_CONSTITUENT (`LAST_NAME`, `FIRST_NAME`) VALUES ('User','Kula');
INSERT INTO CORE_USER (`USER_ID`, `USERNAME`,`PASSWORD`,`ALLOW_AUTH_LOCAL`) VALUES (1, 'kula', '$2y$10$Ek.U.ZmrdSV03stfi/PG7ukuY5ZYOWxa0HUJ9tly9VW81cyLD8HJO', 1);

INSERT INTO CORE_USERGROUP (`USERGROUP_NAME`,`PORTAL`) VALUES ('Core System Administrator', 'core');
INSERT INTO CORE_USER_ROLES (`USER_ID`,`USERGROUP_ID`) VALUES (1, 1);