INSERT INTO CONS_CONSTITUENT (`LAST_NAME`, `FIRST_NAME`) VALUES ('User','Kula');
INSERT INTO CORE_ORGANIZATION (`ORGANIZATION_NAME`, `ORGANIZATION_ABBREVIATION`, `ORGANIZATION_TYPE`, `ACTIVE`) VALUES ('Kula Univeristy', 'KULA', 'S', 1);
INSERT INTO CORE_TERM (`TERM_NAME`, `TERM_ABBREVIATION`, `START_DATE`, `END_DATE`) VALUES ('Kula Term', 'TERM', CURDATE(), CURDATE()+ INTERVAL 1 YEAR);
INSERT INTO CORE_ORGANIZATION_TERMS (`ORGANIZATION_ID`,`TERM_ID`) VALUES (1, 1);
INSERT INTO CORE_USER (`USER_ID`, `USERNAME`,`PASSWORD`,`ALLOW_AUTH_LOCAL`) VALUES (1, 'kula', '$2y$10$Ek.U.ZmrdSV03stfi/PG7ukuY5ZYOWxa0HUJ9tly9VW81cyLD8HJO', 1);


INSERT INTO CORE_USERGROUP (`USERGROUP_NAME`,`PORTAL`) VALUES ('System Administrator', 'core');
INSERT INTO CORE_USER_ROLES (`USER_ID`,`USERGROUP_ID`, `ORGANIZATION_ID`) VALUES (1, 1, 1);

