imports:
    - { resource: parameters.yml }

kula_core_framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    default_locale:  "%locale%"
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    templating:
        engines: ['twig']
    fragments:       ~
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        
      - KulaCoreFrameworkBundle
      - KulaCoreLoginBundle
      - TwigBundle
      - AsseticBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

twig:
  globals:
    instance_name: "%instance_name%"